### ISSUE TITLE
Pyrit handshake Bug 

### ISSUE THREAD

**Issue by deltaxflux** [deltaxflux/flux#6]
it is unable to capturer handshake with pyrit

**Comment by strasharo** [comment]
I think that the issue comes from the fact that during a live capture we often have a truncated capture file, which pyrit doesn't like.

Here's a run with a "complete" pcap file:

```
root@kalif2:/tmp/TMPflux# pyrit -r <obscured>.cap analyze
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file '<obscured>.cap' (1/1)...
Parsed 1 packets (1 802.11-packets), got 1 AP(s)

#1: AccessPoint <obscured> ('TP-LINK_<obscured>'):
No valid EAOPL-handshake + ESSID detected.
root@kalif2:/tmp/TMPflux# 

And here's a run with a truncated pcap file:

root@kalif2:/tmp/TMPflux# pyrit -r <obscured>.cap analyze
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file '<obscured>.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 115, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 163, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 447, in analyze
    parser = self._getParser(capturefile)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 179, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 500, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 488, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 414 captured bytes, only got 158
root@kalif2:/tmp/TMPflux# 

```
As a workaround for that I would like to recommend the following solution:

```
root@kalif2:~# pyrit -r truncated.cap analyze
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file 'truncated.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 115, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 163, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 447, in analyze
    parser = self._getParser(capturefile)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 179, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 500, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 488, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 16 header bytes, only got 2
root@kalif2:~# pyrit -r truncated.cap -o clean.cap stripLive
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing packets from 'truncated.cap'...
1/1: New AccessPoint c4:e9:84:9e:68:26 ('TP-LINK_6826')
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 115, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 163, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 574, in stripLive
    parser.parse_pcapdevice(pckt_rdr)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 500, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 488, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 16 header bytes, only got 2

root@kalif2:~# ls -l truncated.cap clean.cap 
-rw-r--r-- 1 root root    354 Mar  6 13:47 clean.cap
-rw-r--r-- 1 root root 514806 Mar  6 13:46 truncated.cap
root@kalif2:~# 

root@kalif2:~# pyrit -r clean.cap analyze
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file 'clean.cap' (1/1)...
Parsed 1 packets (1 802.11-packets), got 1 AP(s)

#1: AccessPoint <obscured> ('TP-LINK_<obscured>'):
No valid EAOPL-handshake + ESSID detected.
root@kalif2:~# 


```

1) When the user chooses to check for a hanshake create a "clean" pcap file using the stripLive option of pyrit
2) Run pyrit against the "clean" copy in order to check for a HS
3) Run the later verification of password against the "clean" copy of the handshake file.

Let me know if that solution is okay for you and I'll give it a go. :)

**Comment by deltaxflux** [comment]
I prefer solution 2, sure solution 1 is the easiest but i think that fluxion should get more 
automatically. So if you want to fix it you can do it. Futhermore the network-manager bug is because of the checkupdates function. So i deleted the files of the google server because of the danger of damaging the fills (revision part is a bit worse). So hopefully it get the revision part, today done
thanks for sharing & let me about other mistakes

**Comment by strasharo** [comment]
Okay, I'll give it a go later today.:+1:

**Comment by deltaxflux** [comment]
ok nice thank you :+1:

**Comment by strasharo** [comment]
This was easier than I thought, just replaced a file copy operation with stripLive.
